#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building index.ls -> index.js ..."
npx lsc -cp --no-header src/index.ls > dist/index.js
echo "minify index.js -> index.min.js ..."
npx uglifyjs dist/index.js -m -c > dist/index.min.js

#echo "build src/index.styl -> dist/index.css ..."
#./node_modules/.bin/stylus -p src/index.styl > dist/index.css
#echo "minifying index.css ..."
#./node_modules/.bin/uglifycss dist/index.css > dist/index.min.css

echo "copy dist to web ..."
rm -rf web/static/assets/lib/ldscroll/dev/
mkdir -p web/static/assets/lib/ldscroll/dev/
cp -R dist/* web/static/assets/lib/ldscroll/dev/
